### PR TITLE
Fixes notification colors/icons

### LINKED ISSUE #487: Fix notification icon/action colors
Notification icons and actions should follow the system theme (dark or night mode). Need look into what system styles are available.

Part of #423

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #487 

Still have to add `Config` override to declare custom color (See #491)

### CODE REVIEW

File: library/runtime-service-ui/src/androidMain/kotlin/io/matthewnelson/kmp/tor/runtime/service/ui/internal/-Wrappers.kt [hunk 1]
```diff
@@ -15,12 +15,56 @@
...
+    }
+
+    private fun Drawable.toBitmap(pxSize: Int): Bitmap {
+        val bitmap = Bitmap.createBitmap(pxSize, pxSize, Config.ARGB_8888)
+        setBounds(0, 0, pxSize, pxSize)
+        draw(Canvas(bitmap))
+        return bitmap
+    }
+
+    private fun Bitmap.applyColor(size: Int, color: ColorInt): Bitmap {
```
Comment (05nelsonm) [inline library/runtime-service-ui/src/androidMain/kotlin/io/matthewnelson/kmp/tor/runtime/service/ui/internal/-Wrappers.kt:59]: `pxSize`

File: library/runtime-service-ui/src/androidMain/res/layout/kmp_tor_ui_header.xml [hunk 2]
```diff
@@ -21,12 +21,13 @@
...
     android:paddingBottom="4dp">
 
-    <!-- TODO: Circle background -->
     <ImageView
         android:id="@+id/kmp_tor_ui_header_icon"
         android:layout_width="20dp"
         android:layout_height="20dp"
-        android:scaleType="center"
+        android:layout_gravity="center"
+        android:padding="2dp"
```
Comment (05nelsonm) [inline library/runtime-service-ui/src/androidMain/res/layout/kmp_tor_ui_header.xml:29]: Icon being created with h x w `18dp`. Use `1dp` for padding.

Comment (05nelsonm) [reply library/runtime-service-ui/src/androidMain/res/layout/kmp_tor_ui_header.xml:29]: `1dp` looks awful. Not doing.

File: library/runtime-service-ui/src/androidMain/kotlin/io/matthewnelson/kmp/tor/runtime/service/ui/internal/-Wrappers.kt (hunk 1 above)
Comment (05nelsonm) [reply library/runtime-service-ui/src/androidMain/kotlin/io/matthewnelson/kmp/tor/runtime/service/ui/internal/-Wrappers.kt]: Resolved in commit 80926f8
