### PR TITLE
Fix `IllegalStateException` when custom dispatcher is closed.

### LINKED ISSUE #438: Fix closed dispatcher `IllegalStateException` for native
For `TorCtrl` if a new job is launched after dispatchers have been closed then it throws `IllegalStateException` on native, instead of like in Java where it is swallowed.

See https://github.com/05nelsonm/kmp-tor/actions/runs/9436999142/job/25992333969?pr=437#step:10:585

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #438

### CODE REVIEW

**Review by 05nelsonm — COMMENTED** [review]
.

File: library/runtime-ctrl/src/nonJsMain/kotlin/io/matthewnelson/kmp/tor/runtime/ctrl/TorCtrl.kt [hunk 1]
```diff
@@ -206,7 +207,19 @@ public actual interface TorCtrl : Destroyable, TorEvent.Processor, TorCmd.Privil
...
+            val disposable = Disposable {
+                if (disposed) return@Disposable
+                disposed = true
+
+                @OptIn(DelicateCoroutinesApi::class)
+                GlobalScope.launch(CLOSE_DISPATCHER) {
+                    delay(250.milliseconds)
+                    dispatcher.close()
+                }
+            }
```
Comment (05nelsonm) [inline library/runtime-ctrl/src/nonJsMain/kotlin/io/matthewnelson/kmp/tor/runtime/ctrl/TorCtrl.kt:220]: Use `Executable.Once`
