### PR TITLE
Fix dispatching of `AddressInfo` when `unixSocks` paths are opened/closed

### LINKED ISSUE #201: `AddressInfo.unixSocks` not dispatching correctly on config change
Currently the `UnixSocksDiffer` is only taking into account if the `SocksPort` config changed to `0`. This should also take into consideration if `SETCONF` was called for a non-unix domain socket `SocksPort`, b/c it would close all others.

What should occur is, upon opening of a new unix `SocksPort` it is dispatched like regular. Then on config change, the values are added to the list `toKeep`, then all paths for current `AddressInfo.unixSocks` that are not in `toKeep` should be removed and a new `AddressInfo` dispatched.

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #201

### CODE REVIEW

File: library/manager/kmp-tor-manager/src/commonMain/kotlin/io/matthewnelson/kmp/tor/manager/internal/util/UnixSocksDiffer.kt [hunk 1]
```diff
@@ -86,32 +93,18 @@ internal class UnixSocksDiffer(private val torManagerScope: CoroutineScope, priv
...
-        // TODO: Issue #157 use TorConfig.KeyWord
-        if (!output.startsWith(SOCKS_PORT)) return
+        // SocksPort=unix:"/tmp/junit15600960770888728454/tor service/data/socks_test_set.sock" CacheDNS OnionTrafficOnly IsolateSOCKSAuth
+        if (!output.startsWith(SOCKS_PORT_UNIX)) return
 
-        pathsToRemove.withLock {
-            val value = output.substringAfter(SOCKS_PORT)
+        pathsToKeep.withLock {
+            val path = output.substringAfter(SOCKS_PORT_UNIX)
+                .replace("\"", "")
```
Comment (05nelsonm) [inline library/manager/kmp-tor-manager/src/commonMain/kotlin/io/matthewnelson/kmp/tor/manager/internal/util/UnixSocksDiffer.kt:101]: Does not work when flags are present.

Comment (05nelsonm) [reply library/manager/kmp-tor-manager/src/commonMain/kotlin/io/matthewnelson/kmp/tor/manager/internal/util/UnixSocksDiffer.kt]: Resolved in commit a6f9663

**Review by 05nelsonm — COMMENTED** [review]
:+1:
